### ISSUE TITLE
Filter by City and State

### ISSUE THREAD

**Issue by ghost** [jaaybe/covidsearch#5]
### BEHAVIOR OF THE DROP-DOWN LISTS:
- Create two drop-down lists for States and Cities, respectively.
- If a state is selected first by the user, then the drop-down list for cities is narrowed down to only the cities that are in that particular state
- Similarly, if a city is selected first by the user, then the drop-down list for states is narrowed down to only the state(s) that have a city named as selected by the user

### BEHAVIOR OF THE SEARCH BUTTON:
- if the user clicks after s/he has narrowed down the selection of one city/state pair, then covid data is fetched for that city/pair and displayed into the fields planned for by the front-end team
- if the user selection results in multiple city/state pairs (user selected nothing, or only a state, or a city name that can be found in several states), then a warning is displayed asking user if this is truly the selection wanted.
    - if user clicks 'cancel', s/he gets to narrow down selection
    - if user clicks 'confirm, the regular single city/state pair display is replaced with a table displaying all city/state pairs. [Alternatively, we could display the table into a modal, and let the user then select a single city/state pair from that table...]

### BEHAVIOR OF THE CLEAR FILTERS BUTTON:
- restore drop down lists to all states, all cities
---
**NOTE:** At the moment the states and cities are extracted from the covid api to be sure we only list those cities for which we actually have data. In the future, we might want to be exhaustive in terms of cities displayed (and fetch them from another api). We would simply tell the user that we don't have covid data for that city, but we can offer state data and/or the next closest city.

**Comment by natka58** [comment]
I have the drop down ready for you one with city and one with state.

**Comment by PetitsPoissons** [comment]
Noticed a bug with the narrowing down of selections since that feature was merged.
